workflows:
  my-workflow:
    instance_type: mac_mini
    environment:
      flutter: beta
      ndk: default
      xcode: 12.5
      java: 1.8
    scripts:
      - name: Build Android APK
        working_directory: android
      - name: Build with Gradle
        script: gradle build
        script: gradle assembleDebug
    artifacts:
      - app/build/outputs/**/**/*.apk
